apiVersion: 1
datasources:
  - name: Postgres
    uid: postgres
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      maxOpenConns: 50
      maxIdleConns: 10
      connMaxLifetime: 14400
    isDefault: false
    editable: true
