apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secrets
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ include "auth-service.databaseUrl" . | b64enc }}
  jwt-secret-key: {{ .Values.secrets.jwtSecretKey | b64enc }}
  {{- if .Values.secrets.dojaApiKey }}
  doja-api-key: {{ .Values.secrets.dojaApiKey | b64enc }}
  {{- end }}

