services:
  prometheus:
    image: prom/prometheus:latest
    container_name: sandbox-prometheus
    env_file:
      - .env
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:latest
    container_name: sandbox-grafana
    env_file:
      - .env
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:?Set GF_SECURITY_ADMIN_PASSWORD in deployment/monitoring/.env}
      - GRAFANA_RO_USER=${GRAFANA_RO_USER:?Set GRAFANA_RO_USER in deployment/monitoring/.env}
      - GRAFANA_RO_PASSWORD=${GRAFANA_RO_PASSWORD:?Set GRAFANA_RO_PASSWORD in deployment/monitoring/.env}
      - POSTGRES_USER=${POSTGRES_USER:?Set POSTGRES_USER in deployment/monitoring/.env}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Set POSTGRES_PASSWORD in deployment/monitoring/.env}
      - POSTGRES_DB=${POSTGRES_DB:?Set POSTGRES_DB in deployment/monitoring/.env}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ../../docs/dashboards:/var/lib/grafana/dashboards

volumes:
  grafana-storage:
