# Default values for nin service
replicaCount: 1

image:
  repository: ghcr.io/your-org/sandbox-nin-service
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 8005
  targetPort: 8005

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  fsGroup: 2000
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsUser: 1000

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "8005"

secrets:
  databaseUrl: ""
  dojahApiKey: ""

healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: nin.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

networkPolicy:
  enabled: false
  ingress: []
  egress: []
