replicaCount: 1

image:
  repository: ghcr.io/your-org/sandbox-bvn-service
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 8006
  targetPort: 8006

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

env:
  - name: HOST
    value: "0.0.0.0"
  - name: PORT
    value: "8006"

secrets:
  databaseUrl: ""
  dojahApiKey: ""

healthCheck:
  enabled: true
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3



ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: bvn.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

networkPolicy:
  enabled: false
  ingress: []
  egress: []
