apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bvn.secretName" . }}
  labels:
    {{- include "bvn.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.dojahApiKey }}
  dojah-api-key: {{ .Values.secrets.dojahApiKey | b64enc | quote }}
  {{- end }}

