apiVersion: v2
name: config-service
description: A Helm chart for Sandbox Platform Configuration Service
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - config-service
  - configuration
  - microservices
  - fastapi
  - sandbox
home: https://github.com/your-org/sandbox-platform
sources:
  - https://github.com/your-org/sandbox-platform
maintainers:
  - name: Sandbox Platform Team
    email: team@sandbox.example.com
dependencies: []
annotations:
  category: Application

