apiVersion: v1
kind: Secret
metadata:
  name: {{ include "config-service.secretName" . }}
  labels:
    {{- include "config-service.labels" . | nindent 4 }}
type: Opaque
data:
  encryption-key: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  jwt-secret-key: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}

