apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sms.secretName" . }}
  labels:
    {{- include "sms.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.smsApiKey }}
  sms-api-key: {{ .Values.secrets.smsApiKey | b64enc | quote }}
  {{- end }}

