apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-gateway.secretName" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret-key: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}

