name: Build and Deploy
permissions:
  contents: read

on:
  push:
    branches: [main, dev_muhammad]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build images
      run: ./deployment/scripts/build-images.sh -r ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Push images
      run: ./deployment/scripts/push-images.sh -r ${{ secrets.DOCKERHUB_USERNAME }}
