name: Secret Scan (gitleaks)

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  gitleaks:
    name: Run gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          fail: true

      # Optional: Upload SARIF to GitHub Security tab (disabled by default)
      # - name: Upload SARIF
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: gitleaks.sarif

